server:
  port: 8001
spring:
  redis:
    host: 101.33.229.65
    port: 6379
    password: U238ad3@45ASas2243634sf2
  datasource:
    url: jdbc:mysql://101.33.229.65:33306/Dio?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver